### ISSUE TITLE
Tx Accelerator

### ISSUE THREAD

**Issue by VNeBLOB42** [bitpiedotcom/bitpiedotcom.github.com#2]
I submitted an Tx accelerator through BitPie IOS app.  My transaction went through to pay for the service, once this transaction was complete the Accelerator transaction disappeared.  I was able during the time of the transaction to view the Tx Accelerator for my unconfirmed Tx.  Does this mean it is in the works?  why is the Accelerated Tx gone from the lists?

thanks, 
Vince

**Comment by VNeBLOB42** [comment]
I now have 1 confirmation.  thank you.

**Comment by bithernet** [comment]
You are welcome.
